
CURRENCY_TYPE_UAH = 'UAH'
CURRENCY_TYPE_USD = 'USD'
CURRENCY_TYPE_EUR = 'EUR'
CURRENCY_TYPE_BTC = 'BTC'

CURRENCY_TYPES = (
    (CURRENCY_TYPE_UAH, 'Hrivna'),
    (CURRENCY_TYPE_USD, 'Dollar'),
    (CURRENCY_TYPE_EUR, 'Euro'),
    (CURRENCY_TYPE_BTC, 'BitCoin'),
)
