# Generated by Django 4.0.6 on 2022-08-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.FloatField()),
                ('request_method', models.CharField(max_length=6)),
                ('query_params', models.CharField(max_length=124)),
                ('ip', models.CharField(max_length=124)),
                ('path', models.CharField(max_length=124)),
            ],
        ),
        migrations.AlterField(
            model_name='rate',
            name='base_currency_type',
            field=models.CharField(choices=[('UAH', 'Hrivna'), ('USD', 'Dollar'), ('EUR', 'Euro'), ('BTC', 'BitCoin')],
                                   max_length=5),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency_type',
            field=models.CharField(choices=[('UAH', 'Hrivna'), ('USD', 'Dollar'), ('EUR', 'Euro'), ('BTC', 'BitCoin')],
                                   max_length=5),
        ),
    ]
