# Generated by Django 4.0.6 on 2022-09-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_responselog_alter_rate_base_currency_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='source',
        ),
    ]
