# Generated by Django 4.0.6 on 2022-09-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_rate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='code_name',
            field=models.CharField(default='Null', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
